Rule Then's Convert Variables to Named
graknlabs/grakn pull request #5949
Opened 2020-12-15 14:55 UTC by maxbaxt

Please replace every line in curly brackets ( { like this } ) with an appropriate description, and remove this line.

## What is the goal of this PR?

{ In the form of a paragraph (only use bullet points if strictly necessary), please describe the goal of this PR, why they are valuable to achieve, and reference the related GitHub issues. This section will be automatically compiled into the release notes, so please:
  - describe the impact of the change in this PR to the _user_ of this repository (e.g. end user, contributor, developer).
  - describe the new product behaviour in _present tense_, and the old behaviour and how it's been changed in _past tense_.
  - Use the _Royal We_: _"We"_ made changes, not _"I"_ made changes. }

## What are the changes implemented in this PR?

{ Please explain what you implemented, why your changes are the best way to achieve the goal(s) above. Please describe every method, class and package, by explaining:
  - its responsibility, 
  - how it's expected to behave, and 
  - how it relates to the adjacent methods/classes/packages it interacts with. 

This would allow the reviewer to understand your intentions in the code much better. If you're adding new classes, make sure these explanations are also included in the class header comments. Last but not least, please reference the GitHub issues to be automatically closed, such like 'closes #number'. }

2020-12-16 08:51 UTC, maxbaxt commented on logic/Rule.java
> +                 graql.lang.pattern.Conjunction<? extends Pattern> when, graql.lang.pattern.variable.ThingVariable<?> then) {
I think that when we use both analogous objects from both Grakn and Graql, we should use the "long import" for the Object that is foreign to the current repo. Therefore, I've changed all `ThingVariable<?>` to `graql.lang.pattern.variable.ThingVariable<?>` in this PR.

2020-12-21 17:36 UTC, flyingsilverfin commented on logic/Rule.java
> +            if (variable.isThing() && !variable.asThing().has().isEmpty()){
can move the second conditions inside of a single `if` block

2020-12-21 18:09 UTC, flyingsilverfin requested changes

2020-12-21 18:09 UTC, flyingsilverfin commented on pattern/constraint/thing/ValueConstraint.java
> +        public Variable(ThingVariable owner, GraqlToken.Predicate predicate, ThingVariable variable) {
This change is not good - now it makes it look like we can do a say `substring` or `like` (regex) comparision between two variables, which we don't actually support! I'd revert this and undo moving the big `if` switch back into its prior place

2020-12-21 18:09 UTC, flyingsilverfin commented on pattern/variable/ThingVariable.java
> +    public static ThingVariable createTemp(String name) {
these should go into the `ConstraintCopier` imo

2020-12-21 18:09 UTC, flyingsilverfin commented on pattern/variable/ThingVariable.java
> +    public <T> ValueConstraint<?> value(GraqlToken.Predicate comparator, T value) {
these are the big switch statements im talking about

2020-12-21 18:09 UTC, flyingsilverfin commented on pattern/variable/TypeVariable.java
> +    public static TypeVariable createTemp(String name) {
also to `ConstraintCopier` i think, not general enough

2021-01-07 21:42 UTC, flyingsilverfin commented
Superceded by #5977

2021-01-07 21:42 UTC, closed without merging