Port AlphaEquivalence tests from 1.x
graknlabs/grakn pull request #6082
Opened 2021-01-25 18:02 UTC by kasper-piskorski

**For the title of this PR:** please follow the grammatical rules of a usual publication title, without capitalisation (except for the first letter). Thus, the title should NOT CONTAIN CODE: no dots, no parentheses, no backticks, no brackets, etc. It needs to be distinctive (not detailed) and succinct (not lengthy). Details of this PR will go in the description. **For the description of this PR:** please replace every line in curly brackets ( { like this } ) with an appropriate description following the guidance. Finally, **please remove this paragraph**.

## What is the goal of this PR?

{ In the form of a paragraph (only use bullet points if strictly necessary), please describe the goal of this PR, why they are valuable to achieve, and reference the related GitHub issues. This section will be automatically compiled into the release notes, so please:
  - describe the impact of the change in this PR to the _user_ of this repository (e.g. end user, contributor, developer).
  - describe the new product behaviour in _present tense_, and the old behaviour and how it's been changed in _past tense_.
  - Use the _Royal We_: _"We"_ made changes, not _"I"_ made changes. }

## What are the changes implemented in this PR?

{ Please explain what you implemented, why your changes are the best way to achieve the goal(s) above. Please describe every method, class and package, by explaining:
  - its responsibility, 
  - how it's expected to behave, and 
  - how it relates to the adjacent methods/classes/packages it interacts with. 

This would allow the reviewer to understand your intentions in the code much better. If you're adding new classes, make sure these explanations are also included in the class header comments. Last but not least, please reference the GitHub issues to be automatically closed, such like 'closes #number'. }

2021-01-25 21:05 UTC, flyingsilverfin commented on pattern/equivalence/AlphaEquivalenceTest.java
> +    }
variablise so we don't do repeated work + easier to understand

2021-01-25 21:06 UTC, flyingsilverfin commented on pattern/equivalence/AlphaEquivalenceTest.java
> +    private void testAlphaEquivalence(ThingVariable sourceVar, List<ThingVariable> toCheck, Set<Integer> validVars){
can we give this a better name? is this checking alpha equivalence against itself? (reflexive?)

2021-01-25 21:08 UTC, flyingsilverfin commented
I think @jmsfltchr  is the best person to review this - 
i forget exactly how it is right now, but we don't do "fully generic" alpha equivalence... we do an undericted alpha-equivalence walk from a starting constraint by design (it was only intended to test alpha-equivalence of `Concludable` data structures). I haven't looked too closely, i think most of the tests are fine, but I don't necessarily expect all of them to conform and pass :)

leave it here for james!

2021-01-25 21:08 UTC, flyingsilverfin commented on pattern/equivalence/AlphaEquivalenceTest.java
> +    private void testAlphaEquivalence(ThingVariable sourceVar, List<ThingVariable> toCheck, Set<Integer> validVars){
plus better name - `testSymmetricAlphaEquivalence` or something

2021-01-26 14:21 UTC, jmsfltchr requested changes
This is great, I think you tested exactly the bounds of what our alpha equivalence handles. A couple of cases to review. Also we should run these in CI, fix anything broken or `@ignore` them. We'll get you set up on Grabl @kasper-piskorski so that the tests can run there.

2021-01-27 10:32 UTC, kasper-piskorski commented on pattern/equivalence/AlphaEquivalenceTest.java
> +        variables.forEach(var -> testAlphaEquivalenceSymmetricReflexive(var.asThing(), variables, new HashSet<>()));
Yeah, this one's probably over the top.

2021-01-27 10:32 UTC, kasper-piskorski commented on pattern/equivalence/AlphaEquivalenceTest.java
> +        variables.forEach(var -> testAlphaEquivalenceSymmetricReflexive(var.asThing(), variables, new HashSet<>()));
There is no schema backing, which is fine. Even with it how would `$x1 isa organisation` and `$x2 isa company` be alpha-equivalent? I think with tests you should assume nothing so even if it's an uninteresting case it is still useful to have.

2021-01-27 12:36 UTC, flyingsilverfin commented
also don't forget labels and milestones and stuff :)

2021-01-28 09:35 UTC, jmsfltchr commented
> also don't forget labels and milestones and stuff :)

Have added them so that @kasper-piskorski can see how we're doing it.

2021-01-28 09:38 UTC, jmsfltchr commented on pattern/equivalence/AlphaEquivalenceTest.java
> +        variables.forEach(var -> testAlphaEquivalenceSymmetricReflexive(var.asThing(), variables, new HashSet<>()));
Ok that makes sense!

2021-01-28 09:40 UTC, jmsfltchr commented
@kasper-piskorski can you re-run `test-behaviour`, the job failed on Grabl due to a Grabl issue. That should pass. Then, we have a couple of failures from the tests you've added. Could you look and see it the fixes are simple, implement them if so otherwise we can discuss :)

2021-01-28 15:49 UTC, jmsfltchr commented
Note that https://github.com/graknlabs/grakn/pull/6100 may fix issues here!

2021-01-29 18:49 UTC, kasper-piskorski commented
> Note that #6100 may fix failing tests here!

2021-01-29 18:51 UTC, haikalpribadi commented
Why is this PR closed and not merged @kasper-piskorski ?

2021-01-29 18:52 UTC, kasper-piskorski commented
misclicked ;p

2021-02-01 20:26 UTC, jmsfltchr approved these changes

2021-02-01 20:30 UTC, haikalpribadi approved these changes

2021-02-01 20:30 UTC, merged