TODO
graknlabs/grakn pull request #6137
Opened 2021-02-04 18:07 UTC by alexjpwalker

## What is the goal of this PR?

TODO

## What are the changes implemented in this PR?

TODO

2021-02-04 18:52 UTC, haikalpribadi approved these changes

2021-02-05 19:44 UTC, lolski approved these changes

2021-02-06 00:52 UTC, haikalpribadi requested changes
I see what you changed since the last time we discussed this. I like it. Simpler and makes sense. Change the name of `transactionGraphInit()` to `initialisationTransaction()` (for 2 methods) an we're good to go, @lolski @alexjpwalker !

2021-02-08 11:41 UTC, haikalpribadi approved these changes

2021-02-08 11:42 UTC, merged